services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 1234:8080

  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: password
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users_db